import { StyleSheet, Platform } from "react-native";
import { Colors, Fonts, FontSizes, Spacing, Radius, Shadows } from "../constants/theme";

export const dispensaStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Colors.background,
    },
    scrollContent: {
        paddingHorizontal: Spacing.lg,
        paddingTop: Spacing.xl,
        paddingBottom: Spacing.xl * 4, // Espaço extra para o botão flutuante
    },
    title: {
        fontFamily: Fonts.bold,
        fontSize: FontSizes.title,
        color: Colors.dark,
        textAlign: "center",
        marginTop: Spacing.xl,
        marginBottom: Spacing.lg,
    },
    searchContainer: {
        backgroundColor: Colors.light,
        borderRadius: Radius.full,
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: Spacing.md,
        height: 52,
        marginBottom: Spacing.xl,
        overflow: "hidden",
    },
    searchInput: {
        flex: 1,
        fontFamily: Fonts.regular,
        fontSize: FontSizes.medium,
        color: Colors.primary,
        marginLeft: Spacing.sm,
        height: "100%",
        paddingVertical: 0,
        outlineWidth: 0,
    },
    addSection: {
        backgroundColor: Colors.light,
        borderRadius: Radius.lg,
        padding: Spacing.md,
        borderWidth: 1,
        borderColor: Colors.errorLight,
        marginBottom: Spacing.xl,
        ...Shadows.sm,
    },
    sectionLabel: {
        fontFamily: Fonts.bold,
        fontSize: FontSizes.medium,
        color: Colors.dark,
        marginBottom: Spacing.md,
    },
    inputFull: {
        backgroundColor: Colors.light,
        borderRadius: Radius.md,
        height: 48,
        borderWidth: 1,
        borderColor: Colors.errorLight,
        paddingHorizontal: Spacing.md,
        fontFamily: Fonts.regular,
        fontSize: FontSizes.medium,
        marginBottom: Spacing.md,
        color: Colors.subtitle,
        outlineWidth: 0,
    },
    row: {
        flexDirection: "row",
        gap: Spacing.sm,
        alignItems: "center",
    },
    inputSmall: {
        flex: 1,
        height: 48,
        borderRadius: Radius.md,
        borderWidth: 1,
        borderColor: Colors.errorLight,
        textAlign: "center",
        fontFamily: Fonts.regular,
        color: Colors.subtitle,
        outlineWidth: 0,
    },
    pickerContainer: {
        flex: 1.5,
        height: 48,
        borderRadius: Radius.md,
        borderWidth: 1,
        borderColor: Colors.errorLight,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: Spacing.sm,
    },
    btnAdd: {
        backgroundColor: Colors.secondary,
        width: 54,
        height: 48,
        borderRadius: Radius.md,
        justifyContent: "center",
        alignItems: "center",
    },
    ingredientItem: {
        flexDirection: "row",
        paddingVertical: Spacing.md,
        borderBottomWidth: 1,
        borderBottomColor: Colors.light,
        alignItems: "center",
    },
    checkbox: {
        width: 26,
        height: 26,
        borderRadius: Radius.full,
        borderWidth: 2,
        borderColor: Colors.primary,
        justifyContent: "center",
        alignItems: "center",
        marginRight: Spacing.sm,
    },
    checkboxActive: {
        backgroundColor: Colors.primary,
    },
    ingredientInfo: {
        flex: 1,
    },
    ingredientName: {
        fontFamily: Fonts.bold,
        fontSize: FontSizes.medium,
        color: Colors.dark,
        marginBottom: Spacing.xs,
    },
    controlsRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: Spacing.sm / 2,
    },
    listInputQty: {
        width: 55,
        height: 34,
        borderRadius: Radius.full,
        borderWidth: 1,
        borderColor: Colors.errorLight,
        textAlign: "center",
        fontFamily: Fonts.regular,
        fontSize: FontSizes.small,
        color: Colors.subtitle,
        outlineWidth: 0,
        backgroundColor: Colors.light,
    },
    listPickerUnit: {
        width: 75,
        height: 34,
        borderRadius: Radius.full,
        borderWidth: 1,
        borderColor: Colors.errorLight,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 4,
        backgroundColor: Colors.light,
    },
    unitText: {
        fontSize: 13,
        fontFamily: Fonts.regular,
        color: Colors.dark,
    },
    rightIcons: {
        flexDirection: "row",
        alignItems: "center",
        gap: Spacing.md,
        marginLeft: Spacing.sm,
    },
    floatingBtn: {
        position: "absolute",
        bottom: 15,
        left: Spacing.lg,
        right: Spacing.lg,
        backgroundColor: Colors.primary,
        height: 64,
        borderRadius: Radius.full,
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingHorizontal: Spacing.lg,
        ...Shadows.md,
    },
    floatingBtnLeft: {
        flexDirection: "row",
        alignItems: "center",
        gap: Spacing.sm,
    },
    floatingBtnText: {
        color: Colors.light,
        fontFamily: Fonts.bold,
        fontSize: FontSizes.medium,
    },
    badgeContainer: {
        backgroundColor: "rgba(255,255,255,0.25)",
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: Radius.full,
    },
    badgeText: {
        color: Colors.light,
        fontSize: FontSizes.small,
        fontFamily: Fonts.bold,
    },
});