import { StyleSheet, Platform } from "react-native";
import { Colors, Fonts, FontSizes, Spacing, Radius, Shadows } from "../constants/theme";

export const dispensaStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: Colors.background,
    },
    // HEADER FIXO COM TUDO DENTRO
    header: {
        backgroundColor: Colors.light,
        paddingTop: Platform.OS === 'ios' ? Spacing.xl * 2 : Spacing.xl,
        ...Shadows.md,
        zIndex: 10,
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(0,0,0,0.05)',
    },
    titleContainer: {
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(0,0,0,0.05)',
        paddingBottom: Spacing.md,
        marginBottom: Spacing.md,
    },
    title: {
        fontFamily: Fonts.bold,
        fontSize: FontSizes.title,
        color: Colors.dark,
        textAlign: "center",
    },
    headerContent: {
        paddingHorizontal: Spacing.lg,
        paddingBottom: Spacing.lg,
    },
    searchContainer: {
        backgroundColor: Colors.background,
        borderRadius: Radius.full,
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: Spacing.md,
        height: 48,
        borderWidth: 1.5,
        borderColor: 'transparent',
        marginBottom: Spacing.md,
    },
    searchContainerFocused: {
        borderColor: Colors.primary,
        backgroundColor: Colors.light,
    },
    searchInput: {
        flex: 1,
        fontFamily: Fonts.regular,
        fontSize: FontSizes.medium,
        color: Colors.primary,
        marginLeft: Spacing.sm,
        height: "100%",
        // @ts-ignore
        outlineStyle: 'none' as any,
    },
    // SEÇÃO DE ADICIONAR DENTRO DO HEADER
    addSection: {
        backgroundColor: Colors.background,
        borderRadius: Radius.lg,
        padding: Spacing.md,
        borderWidth: 1,
        borderColor: Colors.errorLight,
    },
    sectionLabel: {
        fontFamily: Fonts.bold,
        fontSize: FontSizes.medium,
        color: Colors.dark,
        marginBottom: Spacing.sm,
    },
    inputFull: {
        backgroundColor: Colors.light,
        borderRadius: Radius.md,
        height: 44,
        borderWidth: 1,
        borderColor: Colors.errorLight,
        paddingHorizontal: Spacing.md,
        fontFamily: Fonts.regular,
        fontSize: FontSizes.medium,
        marginBottom: Spacing.sm,
        color: Colors.subtitle,
        // @ts-ignore
        outlineStyle: 'none' as any,
    },
    row: {
        flexDirection: "row",
        gap: Spacing.sm,
        alignItems: "center",
    },
    inputSmall: {
        flex: 1,
        height: 44,
        borderRadius: Radius.md,
        borderWidth: 1,
        borderColor: Colors.errorLight,
        textAlign: "center",
        fontFamily: Fonts.regular,
        color: Colors.subtitle,
        backgroundColor: Colors.light,
        // @ts-ignore
        outlineStyle: 'none' as any,
    },
    pickerContainer: {
        flex: 1.5,
        height: 44,
        borderRadius: Radius.md,
        borderWidth: 1,
        borderColor: Colors.errorLight,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: Spacing.sm,
        backgroundColor: Colors.light,
    },
    btnAdd: {
        backgroundColor: Colors.secondary,
        width: 50,
        height: 44,
        borderRadius: Radius.md,
        justifyContent: "center",
        alignItems: "center",
    },
    // LISTA E ITENS
    scrollContent: {
        paddingHorizontal: Spacing.lg,
        paddingTop: Spacing.md,
        paddingBottom: Spacing.xl * 5,
    },
    ingredientItem: {
        flexDirection: "row",
        paddingVertical: Spacing.md,
        borderBottomWidth: 1,
        borderBottomColor: Colors.light,
        alignItems: "center",
    },
    checkbox: {
        width: 26,
        height: 26,
        borderRadius: Radius.full,
        borderWidth: 2,
        borderColor: Colors.primary,
        justifyContent: "center",
        alignItems: "center",
        marginRight: Spacing.sm,
    },
    checkboxActive: {
        backgroundColor: Colors.primary,
    },
    ingredientInfo: {
        flex: 1,
    },
    ingredientName: {
        fontFamily: Fonts.bold,
        fontSize: FontSizes.medium,
        color: Colors.dark,
        marginBottom: Spacing.xs,
    },
    controlsRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
    },
    listInputQty: {
        width: 55,
        height: 32,
        borderRadius: Radius.full,
        borderWidth: 1,
        borderColor: Colors.errorLight,
        textAlign: "center",
        fontFamily: Fonts.regular,
        fontSize: FontSizes.small,
        color: Colors.subtitle,
        backgroundColor: Colors.light,
        // @ts-ignore
        outlineStyle: 'none' as any,
    },
    listPickerUnit: {
        width: 70,
        height: 32,
        borderRadius: Radius.full,
        borderWidth: 1,
        borderColor: Colors.errorLight,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 4,
        backgroundColor: Colors.light,
    },
    unitText: {
        fontSize: 12,
        fontFamily: Fonts.regular,
        color: Colors.dark,
    },
    rightIcons: {
        marginLeft: Spacing.sm,
    },
    // BOTÃO FLUTUANTE
    floatingBtn: {
        position: "absolute",
        bottom: 20,
        left: Spacing.lg,
        right: Spacing.lg,
        backgroundColor: Colors.primary,
        height: 60,
        borderRadius: Radius.full,
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingHorizontal: Spacing.lg,
        ...Shadows.md,
    },
    floatingBtnLeft: {
        flexDirection: "row",
        alignItems: "center",
        gap: Spacing.sm,
    },
    floatingBtnText: {
        color: Colors.light,
        fontFamily: Fonts.bold,
        fontSize: FontSizes.medium,
    },
    badgeContainer: {
        backgroundColor: "rgba(255,255,255,0.2)",
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: Radius.full,
    },
    badgeText: {
        color: Colors.light,
        fontSize: FontSizes.small,
        fontFamily: Fonts.bold,
    },
});